import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ReduxProvider from "@/components/utils/ReduxProvider";
import { ClerkProvider, auth } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "DineApp Hackathon",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const userId = auth().userId as string;
    return (
        <ClerkProvider>
            <ReduxProvider>
                <html lang="en">
                    <body className={inter.className}>
                        <header>
                            <nav>
                                <Navbar userId={userId} />
                            </nav>
                        </header>
                        <main className="mx-20">{children}</main>
                        <footer>
                            <Footer />
                        </footer>
                    </body>
                </html>
            </ReduxProvider>
        </ClerkProvider>
    );
}
