"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ReduxProvider from "@/components/utils/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ReduxProvider>
            <html lang="en">
                <body className={inter.className}>
                    <header>
                        <nav>
                            <Navbar />
                        </nav>
                    </header>
                    <main className="mx-20">{children}</main>
                    <footer>
                        <Footer />
                    </footer>
                </body>
            </html>
        </ReduxProvider>
    );
}
